# Generated by Django 6.0.2 on 2026-02-15 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pets', '0004_alter_pet_owner'),
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccinated_at', models.DateTimeField(auto_now_add=True)),
                ('next_dose_recommendation', models.DateField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccination_records', to='pets.pet')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccination_records', to='vaccines.vaccine')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccination_records', to='accounts.account')),
            ],
            options={
                'db_table': 'vaccination_records',
                'ordering': ['-vaccinated_at'],
            },
        ),
    ]
