# Generated by Django 6.0.2 on 2026-02-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('address_2', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'owners',
            },
        ),
    ]
